# Generated by Django 5.0 on 2024-01-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="mobile",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="customer",
            name="zipcode",
            field=models.IntegerField(),
        ),
    ]
